export PATH=$PATH:/home/jer/Projet_android/android-ndk-r5/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin/
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../Android.cmake ..
make

# Fix libcsync path in csync executable
# cd buils/client
# change and execute the last link command as below :
#arm-linux-androideabi-gcc -g CMakeFiles/csync_client.dir/csync_client.obj CMakeFiles/csync_client.dir/csync_auth.obj ../src/libcsync.so /home/jer/cm7/manual/argp-standalone-1.3/libargp.a ../src/std/libcstdlib.a /home/jer/cm7/out/target/product/vision/system/lib/libsqlite.so -o csync -I/home/jer/Projet_android/android-ndk-r5/sources/cxx-stl/gnu-libstdc++/include -I/home/jer/Projet_android/android-ndk-r5/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include -I/home/jer/cm7/bionic/libc/arch-arm/include -I/home/jer/cm7/bionic/libc/include -I/home/jer/cm7/bionic/libc/private -I/home/jer/cm7/bionic/libc/kernel/common -I/home/jer/cm7/bionic/libc/kernel/arch-arm -I/home/jer/cm7/bionic/libm/include -I/home/jer/cm7/bionic/libthread_db/include -I/home/jer/cm7/manual/argp-standalone-1.3 -I/home/jer/cm7/manual/libssh/include -I/home/jer/cm7/external/libncurses/include -I/home/jer/cm7/external/expat/lib -I/home/jer/cm7/external/openssl/include -I/home/jer/cm7/external/zlib -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -DANDROID -MMD -MP -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb-interwork -fpic -fno-exceptions -fno-rtti -fexceptions -frtti -ffunction-sections -funwind-tables -fno-short-enums -Wno-psabi -fmessage-length=0 -Wl,--gc-sections -Wl,-z,nocopyreloc -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-rpath-link=/home/jer/cm7/out/target/product/vision/system/lib -L/home/jer/cm7/out/target/product/vision/system/lib -Wl,--fix-cortex-a8 --sysroot=/home/jer/Projet_android/android-ndk-r5/platforms/android-9/arch-arm /home/jer/Projet_android/android-ndk-r5/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/libstdc++.a -lc -lm
#
#arm-linux-androideabi-gcc -g CMakeFiles/csync_client.dir/csync_client.obj CMakeFiles/csync_client.dir/csync_auth.obj /home/jer/cm7/manual/argp-standalone-1.3/libargp.a ../src/std/libcstdlib.a /home/jer/cm7/out/target/product/vision/system/lib/libsqlite.so -o csync -I/home/jer/Projet_android/android-ndk-r5/sources/cxx-stl/gnu-libstdc++/include -I/home/jer/Projet_android/android-ndk-r5/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/include -I/home/jer/cm7/bionic/libc/arch-arm/include -I/home/jer/cm7/bionic/libc/include -I/home/jer/cm7/bionic/libc/private -I/home/jer/cm7/bionic/libc/kernel/common -I/home/jer/cm7/bionic/libc/kernel/arch-arm -I/home/jer/cm7/bionic/libm/include -I/home/jer/cm7/bionic/libthread_db/include -I/home/jer/cm7/manual/argp-standalone-1.3 -I/home/jer/cm7/manual/libssh/include -I/home/jer/cm7/external/libncurses/include -I/home/jer/cm7/external/expat/lib -I/home/jer/cm7/external/openssl/include -I/home/jer/cm7/external/zlib -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -DANDROID -MMD -MP -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -mthumb-interwork -fpic -fno-exceptions -fno-rtti -fexceptions -frtti -ffunction-sections -funwind-tables -fno-short-enums -Wno-psabi -fmessage-length=0 -Wl,--gc-sections -Wl,-z,nocopyreloc -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-rpath-link=/home/jer/cm7/out/target/product/vision/system/lib -L/home/jer/cm7/out/target/product/vision/system/lib -Wl,--fix-cortex-a8 --sysroot=/home/jer/Projet_android/android-ndk-r5/platforms/android-9/arch-arm /home/jer/Projet_android/android-ndk-r5/sources/cxx-stl/gnu-libstdc++/libs/armeabi-v7a/libstdc++.a -lc -lm -L../src -lcsync
